// Generated by CoffeeScript 1.5.0
(function() {
  var onDeletePost;

  $(function() {
    $('.delete_post').click(onDeletePost);
    return $('.send_post').click(function() {
      var _this = this;
      this.content = $('.post_form textarea').val();
      return $.ajax({
        url: '/post',
        type: 'PUT',
        data: JSON.stringify({
          content: this.content
        }),
        success: function(data, status) {
          var po;
          po = $("<li class='post'>\n    <div>" + data.content + "</div>\n    <div class='toolbar'>刚刚<a style='float:right' link='" + data.link + "' class='delete_post' href='javascript:void(0);'>删除</a></div>\n</li>");
          $('.posts').prepend(po);
          $('.delete_post', po).click(onDeletePost);
          return $('.post_form textarea').val('');
        },
        statusCode: {
          400: function() {
            return alert('error');
          }
        }
      });
    });
  });

  onDeletePost = function() {
    var _this = this;
    return $.ajax({
      url: $(this).attr('link'),
      type: 'DELETE',
      success: function(data, status) {
        return $(_this).parents('li').remove();
      },
      statusCode: {
        404: function() {
          return alert('error');
        }
      }
    });
  };

}).call(this);
